<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Textbox_Two_Input_Fields_a</name>
   <tag></tag>
   <elementGuidId>b71d05ff-209e-4b50-b9c3-abd5d14bbde1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id=&quot;gettotal&quot;]//input[@id=&quot;sum1&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//form[@id=&quot;gettotal&quot;]//input[@id=&quot;sum1&quot;]</value>
      <webElementGuid>78cb9021-49f2-4cae-857e-93700f9f39b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
