<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Textbox_Two_Input_Fields_b</name>
   <tag></tag>
   <elementGuidId>cbce8d07-2c3b-423d-bda0-a03110413e65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id=&quot;gettotal&quot;]//input[@id=&quot;sum2&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//form[@id=&quot;gettotal&quot;]//input[@id=&quot;sum2&quot;]</value>
      <webElementGuid>60f229fb-4c69-43c1-997d-957ffeca8b37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
