<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Start_Practicing</name>
   <tag></tag>
   <elementGuidId>6272307f-c676-442e-9f2e-d1cd9dc165db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id=&quot;btn_basic_example&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//a[@id=&quot;btn_basic_example&quot;]</value>
      <webElementGuid>8a524e25-316a-47aa-b74b-12070fec76be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
